default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || '' %>
  pool: 5
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'expert_search' %>
test:
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB'] || 'expert_search_test' %>
production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'expert_search_prod' %>
